### PR TITLE
Re-worked Clear method and small new additions

### PR DESCRIPTION
**Pull request by afarias-br**
* Changed Clear method since it was leading to AVs
* Added new ATemporaryFile param to AddAttachment method
* Added new AddAttachment method overload to create attachments from stream
* Added new ClearAttachments method

### CODE REVIEW

**Review by juliosenha — COMMENTED** [review]
Hello, first thanks for the contribution.....
instead of creating a new variable, can't you check the FIdSMTP.Connected method again?

if FIdSMTP.Connected then
  Self.Disconnect;

**Review by juliosenha — COMMENTED** [review]
image

Could you give me some more details about the Avs ... which version of Delphi and Indy are you using?

Checking some methods was implemented without need, because by default it is already being assigned.

**Comment by afarias-br** [comment]
> Hello, first thanks for the contribution.....

You're welcome.

> instead of creating a new variable, can't you check the FIdSMTP.Connected method again?
> 
> if FIdSMTP.Connected then
> Self.Disconnect;

The goal here is to Disconnct only if not connected before calling SendMail, so you can send more emails connecting only once. So you one calls Connect, it must call Disconnect later (it will not disconnect automaticaly)

**Comment by afarias-br** [comment]
> Could you give me some more details about the Avs ... which version of Delphi and Indy are you using?

Delphi 10.4.1 PRO. Here a code snippet to reproduce the AV:

```
var
  LMail: IMail;
  I: Integer;
begin
  LMail := TMail.New
    .AddFrom('from@mail', 'FromName')
    .SSL(True)
    .Host('smtp.host.com')
    .Port(25)
    .Auth(True)
    .UserName('username')
    .Password('password');

  if LMail.Connect then
  try
    for I := 1 to 2 do
    begin
      if LMail.Clear
          .AddFrom('from@mail', 'FromName')
          .AddTo('some@mail.com', 'Some Name')
          .ContentType('text/html')
          .AddSubject('Some subject')
          .AddBody('<h1>Some text</h1>')
          .AddAttachment('path\to\somefile.pdf')
          .SetUpEmail then
      begin
        LMail.SendMail;
      end;
      Sleep(1000);
    end;
  finally
    LMail.Disconnect;
  end;
```

> Checking some methods was implemented without need, because by default it is already being assigned.

Yes, true. I did not checked. Just tryed to make sure the same assignments that takes place on Create constructor would be aplyed after clearing the Headers, so it would behave exactly as a just created new IMail instance.

**Pull request merged**
